spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

#SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#LOGGING
logging.level.it.schwarz.jobs.review.coupon=DEBUG
logging.level.org.springframework.web=DEBUG